#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-URI-Fetch
Version  : 0.13
Release  : 1
URL      : https://cpan.metacpan.org/authors/id/N/NE/NEILB/URI-Fetch-0.13.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/N/NE/NEILB/URI-Fetch-0.13.tar.gz
Source1  : http://http.debian.net/debian/pool/main/libx/libxml-feed-perl/libxml-feed-perl_0.53+dfsg-1.debian.tar.xz
Summary  : 'Smart URI fetching/caching'
Group    : Development/Tools
License  : Artistic-1.0 Artistic-1.0-Perl GPL-1.0
Requires: perl-URI-Fetch-license
Requires: perl-URI-Fetch-man
Requires: perl(Class::ErrorHandler)
Requires: perl(HTTP::Date)
Requires: perl(HTTP::Request)
Requires: perl(LWP::UserAgent)
Requires: perl(Test::RequiresInternet)
Requires: perl(Try::Tiny)
Requires: perl(URI)
BuildRequires : perl(Class::ErrorHandler)
BuildRequires : perl(HTTP::Date)
BuildRequires : perl(HTTP::Request)
BuildRequires : perl(LWP::UserAgent)
BuildRequires : perl(Test::RequiresInternet)
BuildRequires : perl(Try::Tiny)
BuildRequires : perl(URI)

%description
This archive contains the distribution URI-Fetch,
version 0.13:
Smart URI fetching/caching

%package license
Summary: license components for the perl-URI-Fetch package.
Group: Default

%description license
license components for the perl-URI-Fetch package.


%package man
Summary: man components for the perl-URI-Fetch package.
Group: Default

%description man
man components for the perl-URI-Fetch package.


%prep
tar -xf %{SOURCE1}
cd ..
%setup -q -n URI-Fetch-0.13
mkdir -p %{_topdir}/BUILD/URI-Fetch-0.13/deblicense/
mv %{_topdir}/BUILD/debian/* %{_topdir}/BUILD/URI-Fetch-0.13/deblicense/

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/perl-URI-Fetch
cp LICENSE %{buildroot}/usr/share/doc/perl-URI-Fetch/LICENSE
cp deblicense/copyright %{buildroot}/usr/share/doc/perl-URI-Fetch/deblicense_copyright
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot}
else
./Build install --installdirs=site --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/site_perl/5.26.1/URI/Fetch.pm
/usr/lib/perl5/site_perl/5.26.1/URI/Fetch/Response.pm

%files license
%defattr(-,root,root,-)
/usr/share/doc/perl-URI-Fetch/LICENSE
/usr/share/doc/perl-URI-Fetch/deblicense_copyright

%files man
%defattr(-,root,root,-)
/usr/share/man/man3/URI::Fetch.3
/usr/share/man/man3/URI::Fetch::Response.3
